# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180803_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_years',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='工作年限'),
        ),
    ]
