# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='couese_num',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
