# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180809_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='teacher_avator/default.png', upload_to='teacher_avator/%Y/%m', verbose_name='教师头像'),
        ),
    ]
