# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': '课程分类', 'verbose_name_plural': '课程分类'},
        ),
        migrations.AddField(
            model_name='course',
            name='announcement',
            field=models.TextField(default='', verbose_name='课程公告'),
        ),
    ]
