# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-11 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_teacher_image'),
        ('courses', '0002_course_courseorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='任课教师'),
        ),
    ]
