# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverifyrecord_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user_image/default.png', upload_to='user_image/%Y/%m/', verbose_name='头像'),
        ),
    ]
